config/routes.rb
Rails.application.routes.draw do
  root to: 'guess#index'

  get "guess/" => "guess#index", as: :index

  post "guess/make_guess" => "guess#make_guess", as: :make_guess

  post "guess/correct" => "guess#correct", as: :correct

  post "guess/incorrect" => "guess#incorrect", as: :incorrect

  get "guess/results" => "guess#results", as: :results

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :height, presence: {message: "Please try again"}, numericality: {greater_than: 0}
  validates :weight, presence: {message: "Please try again"}, numericality: {greater_than: 0}
  validates :gender, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/guess_controller.rb
class GuessController < ApplicationController
  include GuessControllerHelper

# POST
  def make_guess
    # Guess based upon linear regression calculation (in helper methods)
    # Get all heights, weights, and genders to base guess upon:
    heights = Person.pluck(:height)
    weights = Person.pluck(:weight)
    genders = Person.pluck(:gender)

    @height = convert_feet_inches(params[:guess][:feet], params[:guess][:inches])
    @weight = params[:guess][:weight]

    @gender_guess = guess(heights, weights, genders, @height, @weight)

    respond_to do |format|
      format.js {render 'make_guess.js.erb'}
    end
  end

#POST
  def correct
    #If guess correct, store gender and correct guess in DB.
    #To-do: Use strong params (with flip_gender and convert_gender_string methods built in somehow)
    person = Person.create(
      height: params[:height],
      weight: params[:weight],
      gender: convert_gender_string(params[:guessed_gender]),#convert string to -1/1 to store.
      guess_correct: true
    )
    if person.save
      redirect_to results_path
    else
      redirect_to :root
      flash[:error] = person.errors.full_messages
    end
  end

# POST
  def incorrect
    #If incorrect, switch gender to store correct gender in DB.
    #To-do: Use strong params (with flip_gender and convert_gender_string methods built in somehow)
    person = Person.create(
      height: params[:height],
      weight: params[:weight],
      gender: flip_gender(params[:guessed_gender]),#convert string to -1/1 to store.
      guess_correct: false
    )
    if person.save
      redirect_to results_path
    else
      redirect_to :root
      flash[:error] = person.errors.full_messages
    end
  end

#GET
  def results
    @num_correct = Person.where(guess_correct:true).length
    @total_num = Person.where(guess_correct:false).length + Person.where(guess_correct:true).length
    @percent = (@num_correct.to_f / @total_num.to_f * 100).round
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guess_controller_helper.rb
module GuessControllerHelper
# Linear Regression calculation to make guess:
  def guess(heights, weights, genders, height_entry, weight_entry)
    @heights, @weights, @genders = heights, weights, genders
    @b0, @b1, @b2 = b0, slope_height, slope_weight

    if @heights.length != @weights.length
      raise "Unbalanced data"
    else
      get_gender_val(height_entry.to_i, weight_entry.to_i)
    end
  end

  def get_gender_val(height, weight)
    val = @b0 + (@b1 * height.to_i) + (@b2 * weight.to_i)
    # Male is > 0, Female is < 0
    return val > 0 ? "Male" : "Female"
  end

  def b0
    mean(@genders) - (slope_height * mean(@heights)) - (slope_weight * mean(@weights))
  end

  def slope_height
    height_mean = mean(@heights)
    weight_mean = mean(@weights)

    numerator = (0...@heights.length).reduce(0) do |sum, i|
      sum + ((@heights[i] - height_mean) * (@weights[i] - weight_mean))
    end

    denominator = @heights.reduce(0) do |sum, x|
      sum + ((x - height_mean) ** 2)
    end

    (numerator / denominator)
  end

  def slope_weight
    height_mean = mean(@heights)
    weight_mean = mean(@weights)

    numerator = (0...@heights.length).reduce(0) do |sum, i|
      sum + ((@heights[i] - height_mean) * (@weights[i] - weight_mean))
    end

    denominator = @heights.reduce(0) do |sum, y|
      sum + ((y - weight_mean) ** 2)
    end

    (numerator / denominator)
  end

  def mean(values)
    total = values.reduce(0) { |sum, x| x + sum }
    Float(total) / Float(values.length)
  end

# Other helper methods to convert data to correct format:
  def convert_gender_string(gender_string)
    case gender_string
    when "Male" then return 1
    when "Female" then return -1
    end
  end

  def flip_gender(gender_string)
    case gender_string
    when "Male" then return -1
    when "Female" then return 1
    end
  end

  def convert_feet_inches(feet, inches)
    return feet.to_i * 12 + inches.to_i
  end

end

app/views/guess/_guess_form.html.erb
<div class="entry">
  <%= simple_form_for :guess, url: make_guess_path, remote: true, html: {class: "input-group center"} do |f| %>
    <%= f.input :feet, input_html: {class: "form-control half"}, placeholder: "Height (ft.)", maxlength: "1", required: true, label: false %>
    <%= f.input :inches, input_html: {class: "form-control half"}, placeholder: "Height (in.)", maxlength: "2", required: true, label: false %>
    <%= f.input :weight, input_html: {class: "form-control"}, placeholder: "Weight (lbs.)", maxlength: "3", required: true, label: false %>
    <%= f.submit "Submit", class: "btn btn-default btn-primary"%>
<% end %>
</div>

app/views/guess/_new_guess.html.erb
<div class="guess">
  <div class="guess_text">
    <h5>My guess is:</h5>
    <h2><%= @gender_guess %></h2>
    <h5>Is this correct?</h5>
  </div>

  <%= button_to 'Yes', { action: 'correct', remote: true, height: @height, weight: @weight,
    guessed_gender: @gender_guess }, {:class => "btn btn-default btn-primary" } %>
  <%= button_to 'No', { action: 'incorrect', remote: true, height: @height, weight: @weight,
    guessed_gender: @gender_guess }, {:class => "btn btn-default btn-primary" } %>
</div>

app/views/guess/_num_correct.html.erb
<div>
  <p>I've guessed <%= @num_correct %> correct out of <%= @total_num %> total guesses </p>
  <%= button_to 'Try Again' %>
</div>

app/views/guess/guess_stats.js.erb
$('.entry').append('<%= j render ("num_correct") %>')

app/views/guess/index.html.erb
<h2>Gender Guess</h2>
<p>Enter your height and weight and I will guess your gender!</p>

<%= render 'guess_form' %>

<% if flash[:error] != nil %>
  <p>INVALID ENTRY. PLEASE TRY AGAIN</p>
  <%= flash[:error] %>
<% end %>

app/views/guess/make_guess.js.erb
$('.entry').append('<%= j render ("new_guess") %>')

app/views/guess/results.html.erb
<div class="results">
  <h4>I've made <span class="red"><%= @num_correct %></span> correct guesses out of <span class="red"><%= @total_num %></span> total guesses for a <span class="red"><%= @percent %></span> percent success rate</h4>
  <h5>Try again?</h5>
  <%= link_to 'Retry', {:action => 'index'}, {:class => "btn btn-default btn-primary" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GenderGuess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>